language: python
python:
- '2.7'
- '3.4'
install:
- pip install django
- django-admin.py startproject --extension=py,.gitignore --template=https://github.com/cirlabs/django-project-template/archive/master.zip aproject
- cd aproject
- pip install -r requirements.txt
script:
- pep8 lib
- pyflakes lib
- coverage run setup.py test
