language: python
python:
- '2.6'
- '2.7'
install:
- pip install django
- django-admin.py startproject --extension=py,.gitignore --template=https://github.com/cirlabs/django-project-template/archive/master.zip project
- cd repo
- pip install -r requirements.txt --use-mirrors
script: 
- python manage.py test
